bias:
  b10_A: 1.6
  b10_B: 1.3
  b2_A: -0.3
  b2_B: -0.3
estimator_keys:
- n
- g
- s
- t
k_range:
  gauss_filter: false
  gauss_filter_kmax: 0.15
  k_max_analysis: 0.35
  k_min_analysis: 0.001
  k_samples: 150
  kmax: 0.5
  kmin: 0.051
keypairs:
- - - n
    - n
  - - all
- - - s
    - n
  - - N
- - - g
    - n
  - - all
- - - t
    - n
  - - N
- - - g
    - g
  - - all
- - - t
    - g
  - - N
- - - g
    - s
  - - N
- - - n
    - ga
  - - N
- - - n
    - sa
  - - N
- - - n
    - ta
  - - N
- - - sa
    - sa
  - - N
- - - g
    - s
  - - N
- - - g
    - t
  - - N
- - - g
    - ga
  - - N
- - - g
    - sa
  - - N
- - - g
    - ta
  - - N
name: desi_base_3_5
number_density:
  nbar_A: 0.00011979378879348753
  nbar_B: 8.984534159511564e-05
output:
  directory: ../results/
  filename_prefix: analysis
physics:
  Fg_factor: 17/21
  a1: 1.0
  a2: -0.8095238095
  deltac: 1.42
power_spectrum:
  linear: linear_power_abacus.txt
  main_directory: ../results/
  nonlinear: nonlinear_power_abacus.txt
sampling:
  Nsamples_base: 7000
sim_params:
  box: 2000
  cleaned_halos: true
  compensated: true
  interlaced: true
  ngrid: 576
  nthread: 128
  paste: TSC
  samples:
  - LRG
  - ELG
  sim_list:
  - 0
  sim_name_base: AbacusSummit_base_c000_ph
  z_mock: 0.5
